issues:
  exclude-use-default: false
  fix: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - errorlint
    - gocognit
    - gocritic
    - gocyclo
    - gomnd
    - gosec
    - revive
    - stylecheck
    - usestdlibvars
    - gofmt

linters-settings:
  gosec:
    excludes:
      - G304
      - G306

  stylecheck:
    checks: [ "all", "-ST1003", "-ST1000" ]

  revive:
    rules:
      - name: package-comments
        disabled: true
